service: icecream-api
frameworkVersion: '2'

provider:
  name: aws
  runtime: java8
  stage: dev
  region: us-east-2
  httpApi:
    authorizers:
      serviceAuthorizer:
        identitySource: $request.header.Authorization
        issuerUrl: <your issuer url here>
        audience: https://auth0-jwt-authorizer
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource: "*"
package:
  artifact: target/${self:service}-${self:provider.stage}.jar

functions:
  ListFlavors:
    handler: com.auth0.ListFlavors
    events:
      - httpApi:
          path: /flavors
          method: get
  ListOrders:
    handler: com.auth0.ListOrders
    events:
      - httpApi:
          path: /orders
          method: get
          authorizer: serviceAuthorizer
  GetOrder:
    handler: com.auth0.GetOrder
    events:
      - httpApi:
          path: /orders/{id}
          method: get
          authorizer: serviceAuthorizer
  CreateOrder:
    handler: com.auth0.CreateOrder
    events:
      - httpApi:
          path: /orders
          method: post
          authorizer: serviceAuthorizer
  UpdateOrder:
    handler: com.auth0.UpdateOrder
    events:
      - httpApi:
          path: /orders/{id}
          method: put
          authorizer: serviceAuthorizer
  DeleteOrder:
    handler: com.auth0.DeleteOrder
    events:
      - httpApi:
          path: /orders/{id}
          method: delete     
          authorizer: serviceAuthorizer     
resources:
  Resources:
    ordersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: orders
        AttributeDefinitions:
          - AttributeName: Id
            AttributeType: S
        KeySchema:
          - AttributeName: Id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
